[alias]
rvx-bundle = ["run", "-p", "xtask", "--", "build-bundle"]
rvx-test-bundle = ["run", "-p", "xtask", "--", "build-test-bundle"]
rvx-run = [
    "run",
    "--release",
    "-p",
    "rvx-cli",
    "--",
    "--firmware",
    "artifacts/out/opensbi/fw_dynamic.bin",
    "--kernel",
    "artifacts/out/linux/Image",
    "--initrd",
    "artifacts/out/rootfs/rootfs.cpio.gz",
    "--append",
    "console=ttyS0 earlycon=sbi root=/dev/ram0 rdinit=/init loglevel=7",
    "--smp",
    "1",
    "--mem",
    "1024",
    "--nographic",
]
rvx-run-smp4 = [
    "run",
    "--release",
    "-p",
    "rvx-cli",
    "--",
    "--firmware",
    "artifacts/out/opensbi/fw_dynamic.bin",
    "--kernel",
    "artifacts/out/linux/Image",
    "--initrd",
    "artifacts/out/rootfs/rootfs.cpio.gz",
    "--append",
    "console=ttyS0 earlycon=sbi root=/dev/ram0 rdinit=/init loglevel=7",
    "--smp",
    "4",
    "--mem",
    "1024",
    "--nographic",
]
rvx-boot = [
    "run",
    "--release",
    "-p",
    "rvx-cli",
    "--",
    "--firmware",
    "artifacts/out/opensbi/fw_dynamic.bin",
    "--kernel",
    "artifacts/out/linux/Image",
    "--initrd",
    "artifacts/out/rootfs/rootfs.cpio.gz",
    "--append",
    "console=ttyS0 earlycon=sbi root=/dev/ram0 rdinit=/init ignore_loglevel initcall_debug loglevel=8",
    "--smp",
    "1",
    "--mem",
    "128",
    "--nographic",
]
rvx-boot-trace = [
    "run",
    "--release",
    "-p",
    "rvx-cli",
    "--",
    "--firmware",
    "artifacts/out/opensbi/fw_dynamic.bin",
    "--kernel",
    "artifacts/out/linux/Image",
    "--initrd",
    "artifacts/out/rootfs/rootfs.cpio.gz",
    "--append",
    "console=ttyS0 earlycon=sbi root=/dev/ram0 rdinit=/init ignore_loglevel initcall_debug loglevel=8",
    "--smp",
    "1",
    "--mem",
    "128",
    "--nographic",
    "--trace",
]
rvx-test-boot = [
    "run",
    "--release",
    "-p",
    "rvx-cli",
    "--",
    "--firmware",
    "artifacts/out/test/opensbi/fw_dynamic.bin",
    "--kernel",
    "artifacts/out/test/linux/Image",
    "--initrd",
    "artifacts/out/test/rootfs/rootfs.cpio.gz",
    "--append",
    "console=ttyS0 earlycon=sbi root=/dev/ram0 rdinit=/init ignore_loglevel loglevel=8",
    "--smp",
    "1",
    "--mem",
    "128",
    "--nographic",
]
